/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cap05.Resueltos.Prestamo;

/**
 *
 * @author Usuario
 */
public class Prestamo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Prestamo.class.getName());

    /**
     * Creates new form Prestamo
     */
    public Prestamo() {
        initComponents();
        setSize(485, 385);
         setLocationRelativeTo(null);   // centrar la ventana
    tiposIntrs = 18;                // número de filas no fijas
    añosMeses = 4;                  // número de columnas no fijas
    jmItemAños.setEnabled(false);
    jPanel1.setBorder(
        new javax.swing.border.TitledBorder("Años del préstamo"));

    // Datos iniciales
    jtfCredito.setText("6000");
    jtfPeriodoMax.setText("1");
    jtfPeriodoMin.setText("1");
    jtfInteresMax.setText("10.00");
    jtfInteresMin.setText("0.00");
    jcbIncremento.setSelectedIndex(2); // incremento

    initTable(tiposIntrs, añosMeses + 1);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfPeriodoMax = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfPeriodoMin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfInteresMax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfInteresMin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbIncremento = new javax.swing.JComboBox<>();
        jLabel01 = new javax.swing.JLabel();
        jtfCredito = new javax.swing.JTextField();
        jbtCalculoPagos = new javax.swing.JButton();
        jbtCalculoAmort = new javax.swing.JButton();
        jScrollPanel1 = new javax.swing.JScrollPane();
        jmnuOpciones = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmnuPrestamoEn = new javax.swing.JMenu();
        jmItemAños = new javax.swing.JMenuItem();
        jmItemMeses = new javax.swing.JMenuItem();
        jmnuAyuda = new javax.swing.JMenu();
        jmItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Duración del préstamo"));

        jLabel2.setText("Máximo:");

        jtfPeriodoMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPeriodoMax.setText("  ");

        jLabel3.setText("Mínimo:");

        jtfPeriodoMin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPeriodoMin.setText("    ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPeriodoMin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfPeriodoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de interés"));

        jLabel4.setText("% máximo:");

        jtfInteresMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("% mínimo:");

        jtfInteresMin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setText("Incremento");

        jcbIncremento.setEditable(true);
        jcbIncremento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.10", "0.25", "0.50", "1.00" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfInteresMin))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfInteresMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel01.setText("Credito:");

        jtfCredito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfCredito.setText(" ");

        jbtCalculoPagos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtCalculoPagos.setText("Pagos");
        jbtCalculoPagos.addActionListener(this::jbtCalculoPagosActionPerformed);

        jbtCalculoAmort.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtCalculoAmort.setText("Amortización");
        jbtCalculoAmort.setDoubleBuffered(true);
        jbtCalculoAmort.setEnabled(false);
        jbtCalculoAmort.addActionListener(this::jbtCalculoAmortActionPerformed);

        jMenu1.setMnemonic('0');
        jMenu1.setText("Opciones");

        jMenuItem1.setMnemonic('I');
        jMenuItem1.setText("Instrucciones");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem2.setMnemonic('S');
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jmnuOpciones.add(jMenu1);

        jmnuPrestamoEn.setMnemonic('P');
        jmnuPrestamoEn.setText("Préstamo en...");

        jmItemAños.setMnemonic('A');
        jmItemAños.setText("Años");
        jmItemAños.addActionListener(this::jmItemAñosMesesActionPerformed);
        jmnuPrestamoEn.add(jmItemAños);

        jmItemMeses.setMnemonic('M');
        jmItemMeses.setText("Meses");
        jmItemMeses.addActionListener(this::jmItemAñosMesesActionPerformed);
        jmnuPrestamoEn.add(jmItemMeses);

        jmnuOpciones.add(jmnuPrestamoEn);

        jmnuAyuda.setMnemonic('A');
        jmnuAyuda.setText("Ayuda");

        jmItemAcercaDe.setText("Acerca De...");
        jmItemAcercaDe.addActionListener(this::jmItemAcercaDeActionPerformed);
        jmnuAyuda.add(jmItemAcercaDe);

        jmnuOpciones.add(jmnuAyuda);

        setJMenuBar(jmnuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel01)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jbtCalculoAmort, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCalculoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel01)
                            .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCalculoPagos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCalculoAmort)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String mensaje;
        mensaje  = "Introduzca el crédito, la duración del préstamo y el tipo\n";
        mensaje += "de interés. Pulse el botón [Pagos] para visualizar\n";
        mensaje += "los pagos mensuales en la rejilla.\n\n";
        mensaje += "Elija un pago mensual y pulse el botón [Amortización]\n";
        mensaje += "para visualizar el plan de amortización para el interés\n";
        mensaje += "y períodos correspondientes al pago elegido.\n\n";
        mensaje += "Para copiar datos en el portapapeles, seleccione las celdas\n";
        mensaje += "que desee y pulse las teclas Ctrl+c.\n";
        javax.swing.JOptionPane.showMessageDialog(
        null, mensaje, "Instrucciones",
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmItemAñosMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemAñosMesesActionPerformed
        // TODO add your handling code here:
        Object item = evt.getSource();
    String tituloMarco = "";

    if (item == jmItemAños) {
        jmItemAños.setEnabled(false);
        jmItemMeses.setEnabled(true);
        tituloMarco = "Años del préstamo";
    } else if (item == jmItemMeses) {
        jmItemAños.setEnabled(true);
        jmItemMeses.setEnabled(false);
        tituloMarco = "Meses del préstamo";
    }
    jPanel1.setBorder(new javax.swing.border.TitledBorder(tituloMarco));
    }//GEN-LAST:event_jmItemAñosMesesActionPerformed

    private void jmItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemAcercaDeActionPerformed
        // TODO add your handling code here:
        String mensaje = "Aplicacion Prestamo Bancario" +
                  "Copyright (c) Marco Pineda";
        javax.swing.JOptionPane.showMessageDialog(
        null, mensaje, "Acerca de Préstamo",
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmItemAcercaDeActionPerformed

    private void jbtCalculoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalculoPagosActionPerformed
         try {
        credito     = Double.parseDouble(jtfCredito.getText());
        periodoMin  = Integer.parseInt(jtfPeriodoMin.getText());
        periodoMax  = Integer.parseInt(jtfPeriodoMax.getText());
        interesMin  = Double.parseDouble(jtfInteresMin.getText());
        interesMax  = Double.parseDouble(jtfInteresMax.getText());
        incremento  = Double.parseDouble((String) jcbIncremento.getSelectedItem());

        // Comprobar que los datos son válidos
        if (credito <= 0 ||
            periodoMin <= 0 || periodoMax <= 0 || periodoMax < periodoMin ||
            interesMin < 0 || interesMax < 0 || interesMax < interesMin)
            throw new NumberFormatException();
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(
            null, "Datos no válidos",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Calcular el n.º de tipos de interés y de periodos
    tiposIntrs = (int) ((interesMax - interesMin) / incremento) + 1;
    añosMeses  = (periodoMax - periodoMin) + 1;

    // Tamaño mínimo de la tabla: los valores iniciales
    int filas = tiposIntrs, cols = añosMeses;
    if (tiposIntrs < 18) filas = 18;
    if (añosMeses  < 4)  cols  = 4;

    // Crear la tabla
    initTable(filas, cols + 1);

    // Almacenar en la columna 0 los tipos de interés
    jtablaCabsFilas.setValueAt(AlinDer("##0.00", interesMin) + "%", 0, 0);
    for (int fila = 1; fila < tiposIntrs; ++fila)
        jtablaCabsFilas.setValueAt(AlinDer("##0.00",
            interesMin + incremento * fila) + "%", fila, 0);

    // Almacenar en la fila 0 las distintas duraciones del préstamo
    javax.swing.table.TableColumn colum = null;
    String per = " años";
    if (jmItemAños.isEnabled()) per = " meses";
    for (int columna = 0; columna < añosMeses; ++columna) {
        colum = jtablaPrestamo.getColumnModel().getColumn(columna);
        colum.setHeaderValue((periodoMin + columna) + per);
    }

    // Los periodos ¿en qué vienen dados? ¿En años o en meses?
    int P = 0;
    if (!jmItemAños.isEnabled())
        P = 12; // son años
    else
        P = 1;  // son meses

    // Calcular pagos
    double interes = 0.0, pagoMens = 0.0;
    int meses;
    for (int fila = 0; fila < tiposIntrs; ++fila) {
        // Obtener el tipo de interés de la fila actual
        String sinteres = jtablaCabsFilas.getValueAt(fila, 0).toString();
        sinteres = sinteres.substring(0, sinteres.indexOf('%'));
        sinteres = sinteres.replace(',', '.');
        interes  = Double.parseDouble(sinteres) / 100 / 12;

        // Calcular los pagos para este tipo de interés
        for (int columna = 0; columna < añosMeses; ++columna) {
            // Obtener la duración del préstamo
            colum = jtablaPrestamo.getColumnModel().getColumn(columna);
            String smeses = (String) colum.getHeaderValue();
            smeses = smeses.substring(0, smeses.indexOf(' '));
            meses  = Integer.parseInt(smeses) * P;

            // Calcular la cantidad a pagar mensualmente
            if (interes == 0.0)
                pagoMens = credito / meses;
            else
                pagoMens = credito * (interes / (1 - (1 /
                    Math.pow(1.0 + interes, (double) meses))));

            // Ponerla en la tabla (se redondea a dos decimales)
            jtablaPrestamo.setValueAt(AlinDer("###,###,##0.00",
                pagoMens), fila, columna);
        }
    }
    tablaPagos = true;
    }//GEN-LAST:event_jbtCalculoPagosActionPerformed

    private void jbtCalculoAmortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalculoAmortActionPerformed
        // TODO add your handling code here:
        // Obtener el tipo de interés correspondiente a la celda seleccionada
    int fila    = jtablaPrestamo.getSelectedRow();
    int columna = jtablaPrestamo.getSelectedColumn();
    String sinteres = (String) jtablaCabsFilas.getValueAt(fila, 0);
    sinteres = sinteres.substring(0, sinteres.indexOf('%'));
    sinteres = sinteres.replace(',', '.');
    double interes = Double.parseDouble(sinteres) / 100 / 12;

    // Obtener el periodo correspondiente a la celda seleccionada
    int P = 0;
    if (!jmItemAños.isEnabled())
        P = 12; // son años
    else
        P = 1;  // son meses
    javax.swing.table.TableColumn colum = null;
    colum = jtablaPrestamo.getColumnModel().getColumn(columna);
    String smeses = (String) colum.getHeaderValue();
    smeses = smeses.substring(0, smeses.indexOf(' '));
    int meses = Integer.parseInt(smeses) * P;
    int filas = meses, cols = 5;
    if (filas < 18) filas = 18;

    // Crear la tabla
    initTable(filas, cols);

    // Almacenar/mostrar en la columna 0 los meses
    for (int mes = 0; mes < meses; ++mes)
        jtablaCabsFilas.setValueAt(AlinDer("#####", mes + 1), mes, 0);

    // Almacenar en la fila 0 las distintas cabeceras
    String cab[] = { "Capital", "Intereses",
                      "Total intereses", "Capital pendiente" };
    for (columna = 0; columna < 4; ++columna) {
        colum = jtablaPrestamo.getColumnModel().getColumn(columna);
        colum.setHeaderValue(cab[columna]);
    }

    // Calcular y mostrar la tabla de amortización.
    double interesesMensuales = 0, capitalMensualAmort = 0,
           totalIntereses = 0, creditoPendiente = credito;
    String formato = "###,###,##0.00";
    for (int mes = 0; mes < meses; ++mes) {
        // Cálculo de los intereses a pagar en el mes actual
        interesesMensuales = creditoPendiente * interes;
        // Cálculo del capital en el mes actual
        capitalMensualAmort = pagoMensual - interesesMensuales;
        // Cálculo del capital pendiente de pagar
        creditoPendiente -= capitalMensualAmort;
        // Cálculo de los intereses totales pagados
        totalIntereses += interesesMensuales;

        // Capital mensual amortizado
        jtablaPrestamo.setValueAt(AlinDer(formato, capitalMensualAmort), mes, 0);
        // Intereses mensuales amortizados
        jtablaPrestamo.setValueAt(AlinDer(formato, interesesMensuales), mes, 1);
        // Total intereses abonados después de este pago
        jtablaPrestamo.setValueAt(AlinDer(formato, totalIntereses), mes, 2);
        // Capital pendiente después de este pago
        jtablaPrestamo.setValueAt(AlinDer(formato, creditoPendiente), mes, 3);
    }
    jbtCalculoAmort.setEnabled(false);
    tablaPagos = false;
    }//GEN-LAST:event_jbtCalculoAmortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Prestamo().setVisible(true));
    }
        private double credito;
        private int periodoMax, periodoMin;
        private double interesMin, interesMax;
        private double incremento;
        private int tiposIntrs, añosMeses;
        private boolean tablaPagos;
        private double pagoMensual;
        
   
    private javax.swing.JTable jtablaPrestamo;
    private javax.swing.JTable jtablaCabsFilas;
    
    private StringBuffer AlinDer(String patron, double dato) {
    java.text.FieldPosition fp =
        new java.text.FieldPosition(java.text.NumberFormat.FRACTION_FIELD);
    java.text.DecimalFormat formato = new java.text.DecimalFormat(patron);
    StringBuffer salida = new StringBuffer();
    formato.format(dato, salida, fp);
    for (int i = 0; i < (patron.length() - fp.getEndIndex()); i++)
        salida.insert(0, ' ');
    return salida;
}
    private void initTable(final int filasTabla, final int colsTabla) {

    class CModeloTablaPrestamo extends javax.swing.table.AbstractTableModel {
        Object dato[][]     = new Object[filasTabla][colsTabla];
        String cabecera[]   = new String[colsTabla];
        boolean editColum[] = new boolean[colsTabla];

        CModeloTablaPrestamo() {
            for (int c = 0; c < colsTabla; ++c) {
                cabecera[c] = "Columna " + c;
                if (c != 0) editColum[c] = true;
            }
        }

       
        public int getColumnCount() { return cabecera.length; }
        public int getRowCount()    { return dato.length; }
        public String getColumnName(int col) { return cabecera[col]; }

        public Object getValueAt(int fila, int col) {
            return dato[fila][col];
        }

        public void setValueAt(Object obj, int fila, int col) {
            dato[fila][col] = obj;
        }

        public boolean isCellEditable(int indFila, int indColum) {
            return editColum[indColum];
        }
    }

    // Crear un modelo de columnas para la tabla préstamo que ignora
    // la primera columna.
    javax.swing.table.TableColumnModel modeloColums =
        new javax.swing.table.DefaultTableColumnModel() {
            boolean primeraCol = true;

            public void addColumn(javax.swing.table.TableColumn col) {
                if (primeraCol) { primeraCol = false; return; }
                col.setMinWidth(110);
                super.addColumn(col);
            }
        };

    // Crear un modelo de columnas para la tabla cabecera de las filas,
    // que solo tenga en cuenta la primera columna.
    javax.swing.table.TableColumnModel modeloCabsFilas =
        new javax.swing.table.DefaultTableColumnModel() {
            boolean primeraCol = true;

            public void addColumn(javax.swing.table.TableColumn col) {
                if (primeraCol) {
                    col.setMaxWidth(55);
                    super.addColumn(col);
                    primeraCol = false;
                }
                // Ignorar el resto de las columnas
            }
        };

    // Crear el modelo de la tabla préstamo
    javax.swing.table.TableModel modeloTabla = new CModeloTablaPrestamo();

    // Crear la tabla préstamo con los modelos pasados como argumentos.
    jtablaPrestamo = new javax.swing.JTable(modeloTabla, modeloColums);

    // Crear la tabla cabecera de las filas.
    jtablaCabsFilas = new javax.swing.JTable(modeloTabla, modeloCabsFilas);

    // Crear las columnas (createDefaultColumnsFromModel utiliza
    // el método getColumnCount definido en TableModel).
    jtablaPrestamo.createDefaultColumnsFromModel();
    jtablaCabsFilas.createDefaultColumnsFromModel();

    // Asegurar el sincronismo entre las dos tablas cuando se
    // realicen selecciones, haciendo que compartan el mismo modelo.
    jtablaPrestamo.setSelectionModel(jtablaCabsFilas.getSelectionModel());

    // Color gris para la cabecera de las filas y hacer la selección
    // sobre la misma invisible.
    jtablaCabsFilas.setBackground(java.awt.Color.lightGray);
    jtablaCabsFilas.setSelectionBackground(java.awt.Color.lightGray);

    // Permitir barras de desplazamiento para ambas tablas
    jtablaPrestamo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    jtablaCabsFilas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

    // Establecer la fuente Courier New
    jtablaPrestamo.setFont(new java.awt.Font("Courier New", 0, 12));
    jtablaCabsFilas.setFont(new java.awt.Font("Courier New", 0, 12));

    // Incluir la tabla préstamo en el panel de desplazamiento
    jScrollPanel1.setViewportView(jtablaPrestamo);

    // Crear una vista para colocar la tabla cabecera de las filas
    // en el mismo panel de desplazamiento que la tabla préstamo.
    javax.swing.JViewport jv = new javax.swing.JViewport();
    jv.setView(jtablaCabsFilas);
    jv.setPreferredSize(jtablaCabsFilas.getMaximumSize());
    jScrollPanel1.setRowHeader(jv);

    // Detectar clic sobre la tabla préstamo
    jtablaPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jtablaPrestamoMouseClicked(evt);
        }
    });
}
    private void jtablaPrestamoMouseClicked(java.awt.event.MouseEvent evt) {
    Object datoCelda = jtablaPrestamo.getValueAt(
        jtablaPrestamo.getSelectedRow(),
        jtablaPrestamo.getSelectedColumn());

    if (datoCelda != null && tablaPagos) {
        // Pasar el número a formato de US necesario para parseDouble
        StringBuffer s = new StringBuffer(datoCelda.toString());
        for (int i = 0; i < s.length(); ++i) {
            if (s.charAt(i) == '.') s.delete(i, i + 1);
            if (s.charAt(i) == ',') s.setCharAt(i, '.');
        }
        // Convertir a double
        pagoMensual = Double.parseDouble(s.toString());
        jbtCalculoAmort.setEnabled(true);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel01;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton jbtCalculoAmort;
    private javax.swing.JButton jbtCalculoPagos;
    private javax.swing.JComboBox<String> jcbIncremento;
    private javax.swing.JMenuItem jmItemAcercaDe;
    private javax.swing.JMenuItem jmItemAños;
    private javax.swing.JMenuItem jmItemMeses;
    private javax.swing.JMenu jmnuAyuda;
    private javax.swing.JMenuBar jmnuOpciones;
    private javax.swing.JMenu jmnuPrestamoEn;
    private javax.swing.JTextField jtfCredito;
    private javax.swing.JTextField jtfInteresMax;
    private javax.swing.JTextField jtfInteresMin;
    private javax.swing.JTextField jtfPeriodoMax;
    private javax.swing.JTextField jtfPeriodoMin;
    // End of variables declaration//GEN-END:variables
}
